Added new repo for beginners
OtacilioN/awesome-hacktoberfest-2021 pull request #323
Opened 2020-10-19 09:20 UTC by vatsalvj

## Contributing

If you want to add a project to this list, please make sure that:

- [ ] You read the [contributing guide](https://github.com/OtacilioN/awesome-hacktoberfest-2020/blob/master/CONTRIBUTING.md)
- [ ] The project can't be just an "add your name" or simply + 1 contribution to hacktoberfest
- [ ] Place them in alphabetical order
- [ ] One repository per PR/contribution - _avoid conflicts and simplify review_
- [ ] Your pull request is not spammy just adding an empty line, otherwise it will be marked as invalid and not count to hacktoberfest.

If they meet the requirements above, feel free to create a PR. Happy Hacking! :sparkles:

2020-10-29 14:30 UTC, OtacilioN requested changes

2020-10-29 14:30 UTC, OtacilioN commented on README.md
> +
can you remove these empty lines?

2020-10-30 16:16 UTC, vatsalvj reviewed
removed the extra lines

2020-10-30 16:16 UTC, vatsalvj commented
removed extra lines

2021-10-01 12:48 UTC, closed without merging