add repo clean code guide javasciprt
OtacilioN/awesome-hacktoberfest-2021 pull request #326
Opened 2020-10-20 02:47 UTC by farisdx66

## Contributing

If you want to add a project to this list, please make sure that:

- [ ] You read the [contributing guide](https://github.com/OtacilioN/awesome-hacktoberfest-2020/blob/master/CONTRIBUTING.md)
- [ ] The project can't be just an "add your name" or simply + 1 contribution to hacktoberfest
- [ ] Place them in alphabetical order
- [ ] One repository per PR/contribution - _avoid conflicts and simplify review_
- [ ] Your pull request is not spammy just adding an empty line, otherwise it will be marked as invalid and not count to hacktoberfest.

If they meet the requirements above, feel free to create a PR. Happy Hacking! :sparkles:

2020-10-29 15:53 UTC, OtacilioN requested changes
Can you fix the conflitcts?

2020-10-29 21:53 UTC, OtacilioN requested changes

2020-10-29 21:53 UTC, OtacilioN commented on README.md
> +
Can you remove this empty line?

2020-10-30 00:45 UTC, farisdx66 commented on README.md
> +
sure

2021-10-01 12:48 UTC, closed without merging